#!/usr/bin/env python3
# -*- coding: utf-8 -*-

INSTRUMENTS = {
    # АИ-100-К5
    "A001CUU025A": {"fuel": "АИ-100-К5", "basis": "НБ Чулман-транс", "transport": "auto"},
    "A001KRU060F": {"fuel": "АИ-100-К5", "basis": "ст. Круглое Поле", "transport": "rail"},
    "A100ANK060F": {"fuel": "АИ-100-К5", "basis": "Ангарск-группа станций", "transport": "rail"},
    "A100NVY060F": {"fuel": "АИ-100-К5", "basis": "ст. Новоярославская", "transport": "rail"},
    "A100STI060F": {"fuel": "АИ-100-К5", "basis": "ст. Стенькино II", "transport": "rail"},
    "A100UFM060F": {"fuel": "АИ-100-К5", "basis": "Уфа-группа станций", "transport": "rail"},
    "A100VRZ005A": {"fuel": "АИ-100-К5", "basis": "Воронежский цех", "transport": "auto"},
    "A106NPT005A": {"fuel": "АИ-100-К5", "basis": "ТАНЕКО", "transport": "auto"},
    "A106PDK060F": {"fuel": "АИ-100-К5", "basis": "Предкомбинатская-группа станций", "transport": "rail"},
    "A106PDK060J": {"fuel": "АИ-100-К5", "basis": "Предкомбинатская-группа станций", "transport": "rail"},
    "A10KZLY060W": {"fuel": "АИ-100-К5", "basis": "ст. Злынка-Экспорт", "transport": "rail"},
    
    # АИ-92-К5
    "A692ACH005A": {"fuel": "АИ-92-К5", "basis": "Ачинский НПЗ", "transport": "auto"},
    "A692ALL060J": {"fuel": "АИ-92-К5", "basis": "ст. Аллагуват", "transport": "rail"},
    "A692ANK060F": {"fuel": "АИ-92-К5", "basis": "Ангарск-группа станций", "transport": "rail"},
    "A692ASO005A": {"fuel": "АИ-92-К5", "basis": "АСН Сургутский ЗСК", "transport": "auto"},
    "A692AVM005A": {"fuel": "АИ-92-К5", "basis": "СН КНПЗ", "transport": "auto"},
    "A692BIN060J": {"fuel": "АИ-92-К5", "basis": "ст. Биклянь", "transport": "rail"},
    "A692BTC060J": {"fuel": "АИ-92-К5", "basis": "БП (б.т.ц.) Осенцы", "transport": "rail"},
    "A692CEV010A": {"fuel": "АИ-92-К5", "basis": "Челябинская НБ", "transport": "auto"},
    "A692CIL060F": {"fuel": "АИ-92-К5", "basis": "ст. Цильна", "transport": "rail"},
    "A692DZM060F": {"fuel": "АИ-92-К5", "basis": "ст. Дземги", "transport": "rail"},
    "A692JEF005A": {"fuel": "АИ-92-К5", "basis": "НБ Энгельская", "transport": "auto"},
    "A692KDM005A": {"fuel": "АИ-92-К5", "basis": "НБ Кудьминская", "transport": "auto"},
    "A692KGY005A": {"fuel": "АИ-92-К5", "basis": "НБ Когалым", "transport": "auto"},
    "A692KOB060F": {"fuel": "АИ-92-К5", "basis": "ст. Комбинатская", "transport": "rail"},
    "A692LTN025A": {"fuel": "АИ-92-К5", "basis": "НБ Латная", "transport": "auto"},
    "A692LUL060J": {"fuel": "АИ-92-К5", "basis": "Волгоград-группа станций", "transport": "rail"},
    "A692MID005A": {"fuel": "АИ-92-К5", "basis": "Минеральные воды", "transport": "auto"},
    "A692NIL060F": {"fuel": "АИ-92-К5", "basis": "ст. Никель", "transport": "rail"},
    "A692NIL060J": {"fuel": "АИ-92-К5", "basis": "ст. Никель", "transport": "rail"},
    "A692NOV060F": {"fuel": "АИ-92-К5", "basis": "ст. Новая Еловка", "transport": "rail"},
    "A692NVY060F": {"fuel": "АИ-92-К5", "basis": "ст. Новоярославская", "transport": "rail"},
    "A692OSN060F": {"fuel": "АИ-92-К5", "basis": "ст. Осенцы", "transport": "rail"},
    "A692PIP005A": {"fuel": "АИ-92-К5", "basis": "НБ Приоритет", "transport": "auto"},
    "A692PTD005A": {"fuel": "АИ-92-К5", "basis": "НБ Петрозаводская", "transport": "auto"},
    "A692PUP060F": {"fuel": "АИ-92-К5", "basis": "ст. Пурпе", "transport": "rail"},
    "A692REN025A": {"fuel": "АИ-92-К5", "basis": "НБ РЕНЕКО-С", "transport": "auto"},
    "A692RFF060C": {"fuel": "АИ-92-К5", "basis": "РФ БП", "transport": "rail"},
    "A692ROD005A": {"fuel": "АИ-92-К5", "basis": "Ростов-на-Дону БП", "transport": "auto"},
    "A692ROR005A": {"fuel": "АИ-92-К5", "basis": "НБ Серпуховская", "transport": "auto"},
    "A692RSN005A": {"fuel": "АИ-92-К5", "basis": "Краснодар БП", "transport": "auto"},
    "A692RTH005A": {"fuel": "АИ-92-К5", "basis": "Ртищевская НБ", "transport": "auto"},
    "A692SAU060F": {"fuel": "АИ-92-К5", "basis": "Самара-группа станций", "transport": "rail"},
    "A692SDZ060J": {"fuel": "АИ-92-К5", "basis": "ст. Судженка", "transport": "rail"},
    "A692SSI060F": {"fuel": "АИ-92-К5", "basis": "Саратов-группа станций", "transport": "rail"},
    "A692STI060F": {"fuel": "АИ-92-К5", "basis": "ст. Стенькино II", "transport": "rail"},
    "A692SUR060J": {"fuel": "АИ-92-К5", "basis": "ст. Сургут", "transport": "rail"},
    "A692SVS005A": {"fuel": "АИ-92-К5", "basis": "Увекская НБ", "transport": "auto"},
    "A692SVZ005A": {"fuel": "АИ-92-К5", "basis": "НБ Связь-Петролеум", "transport": "auto"},
    "A692SZE005A": {"fuel": "АИ-92-К5", "basis": "Стрежевской НПЗ", "transport": "auto"},
    "A692UFM060F": {"fuel": "АИ-92-К5", "basis": "Уфа-группа станций", "transport": "rail"},
    "A692UFS010A": {"fuel": "АИ-92-К5", "basis": "Уфимская НБ", "transport": "auto"},
    "A692URF005A": {"fuel": "АИ-92-К5", "basis": "ТПП Урайнефтегаз", "transport": "auto"},
    "A692URT005A": {"fuel": "АИ-92-К5", "basis": "Сургут-25 БП", "transport": "auto"},
    "A692VRL005A": {"fuel": "АИ-92-К5", "basis": "Воронеж-Липецк БП", "transport": "auto"},
    "A692YAI060F": {"fuel": "АИ-92-К5", "basis": "ст. Яничкино", "transport": "rail"},
    "A692ZEL060J": {"fuel": "АИ-92-К5", "basis": "ст. Зелецино", "transport": "rail"},
    "A925KII060F": {"fuel": "АИ-92-К5", "basis": "ст. Кириши", "transport": "rail"},
    "A925KIT025A": {"fuel": "АИ-92-К5", "basis": "КИНЕФ", "transport": "auto"},
    "A926NPT005A": {"fuel": "АИ-92-К5", "basis": "ТАНЕКО", "transport": "auto"},
    "A926PDK060J": {"fuel": "АИ-92-К5", "basis": "Предкомбинатская-группа станций", "transport": "rail"},
    "A92KRUY060W": {"fuel": "АИ-92-К5", "basis": "ст. Рудня-Экспорт", "transport": "rail"},
    "A92KZAH060W": {"fuel": "АИ-92-К5", "basis": "ст. Завережье-Экспорт", "transport": "rail"},
    "A92KZLY060W": {"fuel": "АИ-92-К5", "basis": "ст. Злынка-Экспорт", "transport": "rail"},
    
    # АИ-95-К5
    "A695ACH005A": {"fuel": "АИ-95-К5", "basis": "Ачинский НПЗ", "transport": "auto"},
    "A695ALL060J": {"fuel": "АИ-95-К5", "basis": "ст. Аллагуват", "transport": "rail"},
    "A695ANK060F": {"fuel": "АИ-95-К5", "basis": "Ангарск-группа станций", "transport": "rail"},
    "A695ASO005A": {"fuel": "АИ-95-К5", "basis": "АСН Сургутский ЗСК", "transport": "auto"},
    "A695AVM005A": {"fuel": "АИ-95-К5", "basis": "СН КНПЗ", "transport": "auto"},
    "A695BPI060J": {"fuel": "АИ-95-К5", "basis": "БП (б.т.ц.) Войновка", "transport": "rail"},
    "A695BSA005A": {"fuel": "АИ-95-К5", "basis": "Балашовская НБ", "transport": "auto"},
    "A695BTC060J": {"fuel": "АИ-95-К5", "basis": "БП (б.т.ц.) Осенцы", "transport": "rail"},
    "A695CEV010A": {"fuel": "АИ-95-К5", "basis": "Челябинская НБ", "transport": "auto"},
    "A695DZM060F": {"fuel": "АИ-95-К5", "basis": "ст. Дземги", "transport": "rail"},
    "A695ENU025A": {"fuel": "АИ-95-К5", "basis": "Елховский НПЗ", "transport": "auto"},
    "A695KGY005A": {"fuel": "АИ-95-К5", "basis": "НБ Когалым", "transport": "auto"},
    "A695KII060F": {"fuel": "АИ-95-К5", "basis": "ст. Кириши", "transport": "rail"},
    "A695KIT025A": {"fuel": "АИ-95-К5", "basis": "КИНЕФ", "transport": "auto"},
    "A695LSS005A": {"fuel": "АИ-95-К5", "basis": "Лискинский цех", "transport": "auto"},
    "A695LUL060J": {"fuel": "АИ-95-К5", "basis": "Волгоград-группа станций", "transport": "rail"},
    "A695MID005A": {"fuel": "АИ-95-К5", "basis": "Минеральные воды", "transport": "auto"},
    "A695NOV060F": {"fuel": "АИ-95-К5", "basis": "ст. Новая Еловка", "transport": "rail"},
    "A695NVY060F": {"fuel": "АИ-95-К5", "basis": "ст. Новоярославская", "transport": "rail"},
    "A695PIP005A": {"fuel": "АИ-95-К5", "basis": "НБ Приоритет", "transport": "auto"},
    "A695RFF060C": {"fuel": "АИ-95-К5", "basis": "РФ БП", "transport": "rail"},
    "A695ROR005A": {"fuel": "АИ-95-К5", "basis": "НБ Серпуховская", "transport": "auto"},
    "A695SAU060F": {"fuel": "АИ-95-К5", "basis": "Самара-группа станций", "transport": "rail"},
    "A695SDZ060J": {"fuel": "АИ-95-К5", "basis": "ст. Судженка", "transport": "rail"},
    "A695SSI060F": {"fuel": "АИ-95-К5", "basis": "Саратов-группа станций", "transport": "rail"},
    "A695STI060F": {"fuel": "АИ-95-К5", "basis": "ст. Стенькино II", "transport": "rail"},
    "A695SVS005A": {"fuel": "АИ-95-К5", "basis": "Увекская НБ", "transport": "auto"},
    "A695SVZ005A": {"fuel": "АИ-95-К5", "basis": "НБ Связь-Петролеум", "transport": "auto"},
    "A695UFM060F": {"fuel": "АИ-95-К5", "basis": "Уфа-группа станций", "transport": "rail"},
    "A695UFS010A": {"fuel": "АИ-95-К5", "basis": "Уфимская НБ", "transport": "auto"},
    "A695URT005A": {"fuel": "АИ-95-К5", "basis": "Сургут-25 БП", "transport": "auto"},
    "A695VLA060J": {"fuel": "АИ-95-К5", "basis": "ст. Ветласян", "transport": "rail"},
    "A695VON060J": {"fuel": "АИ-95-К5", "basis": "ст. Войновка", "transport": "rail"},
    "A695VRZ005A": {"fuel": "АИ-95-К5", "basis": "Воронежский цех", "transport": "auto"},
    "A695YAI060F": {"fuel": "АИ-95-К5", "basis": "ст. Яничкино", "transport": "rail"},
    "A695YAI060J": {"fuel": "АИ-95-К5", "basis": "ст. Яничкино", "transport": "rail"},
    "A695ZEL060J": {"fuel": "АИ-95-К5", "basis": "ст. Зелецино", "transport": "rail"},
    "A953KOB060F": {"fuel": "АИ-95-К5", "basis": "ст. Комбинатская", "transport": "rail"},
    "A956NPT005A": {"fuel": "АИ-95-К5", "basis": "ТАНЕКО", "transport": "auto"},
    "A956PDK060J": {"fuel": "АИ-95-К5", "basis": "Предкомбинатская-группа станций", "transport": "rail"},
    "A95KZLY060W": {"fuel": "АИ-95-К5", "basis": "ст. Злынка-Экспорт", "transport": "rail"},
    
    # ДТ-А-К5 (Арктика)
    "DA54NPT025A": {"fuel": "ДТ-А-К5 (Арктика)", "basis": "ТАНЕКО", "transport": "auto"},
    "DA54PDK065J": {"fuel": "ДТ-А-К5 (Арктика)", "basis": "Предкомбинатская-группа станций", "transport": "rail"},
    "DA54RFF060C": {"fuel": "ДТ-А-К5 (Арктика)", "basis": "РФ БП", "transport": "rail"},
    "DT54ASO005A": {"fuel": "ДТ-А-К5 (Арктика)", "basis": "АСН Сургутский ЗСК", "transport": "auto"},
    "DT54MEO005A": {"fuel": "ДТ-А-К5 (Арктика)", "basis": "Мегион-150 БП", "transport": "auto"},
    "DT54SUR065J": {"fuel": "ДТ-А-К5 (Арктика)", "basis": "ст. Сургут", "transport": "rail"},
    "DT54URT005A": {"fuel": "ДТ-А-К5 (Арктика)", "basis": "Сургут-25 БП", "transport": "auto"},
    "DW51KII065F": {"fuel": "ДТ-А-К5 (Арктика)", "basis": "ст. Кириши", "transport": "rail"},
    
    # ДТ-З-К5 (Зимнее)
    "DE13ENU025A": {"fuel": "ДТ-З-К5 (Зимнее)", "basis": "Елховский НПЗ", "transport": "auto"},
    "DE15SYC005A": {"fuel": "ДТ-З-К5 (Зимнее)", "basis": "НБ Сызранская", "transport": "auto"},
    "DE15VRZ005A": {"fuel": "ДТ-З-К5 (Зимнее)", "basis": "Воронежский цех", "transport": "auto"},
    "DE35KGY005A": {"fuel": "ДТ-З-К5 (Зимнее)", "basis": "НБ Когалым", "transport": "auto"},
    "DT2ENPT025A": {"fuel": "ДТ-З-К5 (Зимнее)", "basis": "ТАНЕКО", "transport": "auto"},
    "DT32NVY065F": {"fuel": "ДТ-З-К5 (Зимнее)", "basis": "ст. Новоярославская", "transport": "rail"},
    "DT32OLN005A": {"fuel": "ДТ-З-К5 (Зимнее)", "basis": "НБ Оленегорская", "transport": "auto"},
    "DW25ACH005A": {"fuel": "ДТ-З-К5 (Зимнее)", "basis": "Ачинский НПЗ", "transport": "auto"},
    "DW25ALL065J": {"fuel": "ДТ-З-К5 (Зимнее)", "basis": "ст. Аллагуват", "transport": "rail"},
    "DW25ANK065F": {"fuel": "ДТ-З-К5 (Зимнее)", "basis": "Ангарск-группа станций", "transport": "rail"},
    "DW25AVM005A": {"fuel": "ДТ-З-К5 (Зимнее)", "basis": "СН КНПЗ", "transport": "auto"},
    "DW25BIN065J": {"fuel": "ДТ-З-К5 (Зимнее)", "basis": "ст. Биклянь", "transport": "rail"},
    "DW25CEV010A": {"fuel": "ДТ-З-К5 (Зимнее)", "basis": "Челябинская НБ", "transport": "auto"},
    "DW25DZM065F": {"fuel": "ДТ-З-К5 (Зимнее)", "basis": "ст. Дземги", "transport": "rail"},
    "DW25LOI010A": {"fuel": "ДТ-З-К5 (Зимнее)", "basis": "НБ Лосиная", "transport": "auto"},
    "DW25NOV065F": {"fuel": "ДТ-З-К5 (Зимнее)", "basis": "ст. Новая Еловка", "transport": "rail"},
    "DW25OTA005A": {"fuel": "ДТ-З-К5 (Зимнее)", "basis": "ТАИФ-НК", "transport": "auto"},
    "DW25PDK065J": {"fuel": "ДТ-З-К5 (Зимнее)", "basis": "Предкомбинатская-группа станций", "transport": "rail"},
    "DW25PUP065F": {"fuel": "ДТ-З-К5 (Зимнее)", "basis": "ст. Пурпе", "transport": "rail"},
    "DW25RFF060C": {"fuel": "ДТ-З-К5 (Зимнее)", "basis": "РФ БП", "transport": "rail"},
    "DW25TUY010A": {"fuel": "ДТ-З-К5 (Зимнее)", "basis": "Туймазинская НБ", "transport": "auto"},
    "DW25UFM065F": {"fuel": "ДТ-З-К5 (Зимнее)", "basis": "Уфа-группа станций", "transport": "rail"},
    "DW25UFS010A": {"fuel": "ДТ-З-К5 (Зимнее)", "basis": "Уфимская НБ", "transport": "auto"},
    "DW25VON065J": {"fuel": "ДТ-З-К5 (Зимнее)", "basis": "ст. Войновка", "transport": "rail"},
    "DW32NIL065F": {"fuel": "ДТ-З-К5 (Зимнее)", "basis": "ст. Никель", "transport": "rail"},
    "DW35KII065F": {"fuel": "ДТ-З-К5 (Зимнее)", "basis": "ст. Кириши", "transport": "rail"},
    "DW35KIT025A": {"fuel": "ДТ-З-К5 (Зимнее)", "basis": "КИНЕФ", "transport": "auto"},
    
    # ДТ-Е-К5 (Межсезон)
    "DE5EBIN065J": {"fuel": "ДТ-Е-К5 (Межсезон)", "basis": "ст. Биклянь", "transport": "rail"},
    "DE5EBTC065J": {"fuel": "ДТ-Е-К5 (Межсезон)", "basis": "БП (б.т.ц.) Осенцы", "transport": "rail"},
    "DE5EKAM065F": {"fuel": "ДТ-Е-К5 (Межсезон)", "basis": "ст. Кама", "transport": "rail"},
    "DE5EKDM005A": {"fuel": "ДТ-Е-К5 (Межсезон)", "basis": "НБ Кудьминская", "transport": "auto"},
    "DE5EKHE062J": {"fuel": "ДТ-Е-К5 (Межсезон)", "basis": "ст. Коченево", "transport": "rail"},
    "DE5EKII065F": {"fuel": "ДТ-Е-К5 (Межсезон)", "basis": "ст. Кириши", "transport": "rail"},
    "DE5ENIL065F": {"fuel": "ДТ-Е-К5 (Межсезон)", "basis": "ст. Никель", "transport": "rail"},
    "DE5ENIL065J": {"fuel": "ДТ-Е-К5 (Межсезон)", "basis": "ст. Никель", "transport": "rail"},
    "DE5ENOV065F": {"fuel": "ДТ-Е-К5 (Межсезон)", "basis": "ст. Новая Еловка", "transport": "rail"},
    "DE5ENPT025A": {"fuel": "ДТ-Е-К5 (Межсезон)", "basis": "ТАНЕКО", "transport": "auto"},
    "DE5EOSN065F": {"fuel": "ДТ-Е-К5 (Межсезон)", "basis": "ст. Осенцы", "transport": "rail"},
    "DE5EPDK065J": {"fuel": "ДТ-Е-К5 (Межсезон)", "basis": "Предкомбинатская-группа станций", "transport": "rail"},
    "DE5EPIP005A": {"fuel": "ДТ-Е-К5 (Межсезон)", "basis": "НБ Приоритет", "transport": "auto"},
    "DE5EPUN005A": {"fuel": "ДТ-Е-К5 (Межсезон)", "basis": "Пункт автоналива (ЯНОС)", "transport": "auto"},
    "DE5EREN025A": {"fuel": "ДТ-Е-К5 (Межсезон)", "basis": "НБ РЕНЕКО-С", "transport": "auto"},
    "DE5ERFF060C": {"fuel": "ДТ-Е-К5 (Межсезон)", "basis": "РФ БП", "transport": "rail"},
    "DE5EROR005A": {"fuel": "ДТ-Е-К5 (Межсезон)", "basis": "НБ Серпуховская", "transport": "auto"},
    "DE5ESAU065F": {"fuel": "ДТ-Е-К5 (Межсезон)", "basis": "Самара-группа станций", "transport": "rail"},
    "DE5ESSI065F": {"fuel": "ДТ-Е-К5 (Межсезон)", "basis": "Саратов-группа станций", "transport": "rail"},
    "DE5ESTI065F": {"fuel": "ДТ-Е-К5 (Межсезон)", "basis": "ст. Стенькино II", "transport": "rail"},
    "DE5EUFM065F": {"fuel": "ДТ-Е-К5 (Межсезон)", "basis": "Уфа-группа станций", "transport": "rail"},
    "DE5EVON065J": {"fuel": "ДТ-Е-К5 (Межсезон)", "basis": "ст. Войновка", "transport": "rail"},
    "DE5EZEL065J": {"fuel": "ДТ-Е-К5 (Межсезон)", "basis": "ст. Зелецино", "transport": "rail"},
    "DE5FLUL065J": {"fuel": "ДТ-Е-К5 (Межсезон)", "basis": "Волгоград-группа станций", "transport": "rail"},
    "DE5FNVY065F": {"fuel": "ДТ-Е-К5 (Межсезон)", "basis": "ст. Новоярославская", "transport": "rail"},
    "DE5FROR005A": {"fuel": "ДТ-Е-К5 (Межсезон)", "basis": "НБ Серпуховская", "transport": "auto"},
    "DT20RUY060W": {"fuel": "ДТ-Е-К5 (Межсезон)", "basis": "ст. Рудня-Экспорт", "transport": "rail"},
    "DT20ZAH060W": {"fuel": "ДТ-Е-К5 (Межсезон)", "basis": "ст. Завережье-Экспорт", "transport": "rail"},
    
    # ДТ-Л-К5 (Летнее)
    "DSC5ALL065J": {"fuel": "ДТ-Л-К5 (Летнее)", "basis": "ст. Аллагуват", "transport": "rail"},
    "DSC5ANK065F": {"fuel": "ДТ-Л-К5 (Летнее)", "basis": "Ангарск-группа станций", "transport": "rail"},
    "DSC5BTC065J": {"fuel": "ДТ-Л-К5 (Летнее)", "basis": "БП (б.т.ц.) Осенцы", "transport": "rail"},
    "DSC5DZM065F": {"fuel": "ДТ-Л-К5 (Летнее)", "basis": "ст. Дземги", "transport": "rail"},
    "DSC5GUB005A": {"fuel": "ДТ-Л-К5 (Летнее)", "basis": "НБ Губкинская", "transport": "auto"},
    "DSC5KII065F": {"fuel": "ДТ-Л-К5 (Летнее)", "basis": "ст. Кириши", "transport": "rail"},
    "DSC5KOB065F": {"fuel": "ДТ-Л-К5 (Летнее)", "basis": "ст. Комбинатская", "transport": "rail"},
    "DSC5KSC005A": {"fuel": "ДТ-Л-К5 (Летнее)", "basis": "НБ Косыревская", "transport": "auto"},
    "DSC5LSS005A": {"fuel": "ДТ-Л-К5 (Летнее)", "basis": "Лискинский цех", "transport": "auto"},
    "DSC5LUL065J": {"fuel": "ДТ-Л-К5 (Летнее)", "basis": "Волгоград-группа станций", "transport": "rail"},
    "DSC5LVI025A": {"fuel": "ДТ-Л-К5 (Летнее)", "basis": "НБ Ливенская", "transport": "auto"},
    "DSC5NVY065F": {"fuel": "ДТ-Л-К5 (Летнее)", "basis": "ст. Новоярославская", "transport": "rail"},
    "DSC5OSN065F": {"fuel": "ДТ-Л-К5 (Летнее)", "basis": "ст. Осенцы", "transport": "rail"},
    "DSC5POF005A": {"fuel": "ДТ-Л-К5 (Летнее)", "basis": "НБ Пром-Нефть-Сервис", "transport": "auto"},
    "DSC5RFF060C": {"fuel": "ДТ-Л-К5 (Летнее)", "basis": "РФ БП", "transport": "rail"},
    "DSC5SAU065F": {"fuel": "ДТ-Л-К5 (Летнее)", "basis": "Самара-группа станций", "transport": "rail"},
    "DSC5SSI065F": {"fuel": "ДТ-Л-К5 (Летнее)", "basis": "Саратов-группа станций", "transport": "rail"},
    "DSC5STI065F": {"fuel": "ДТ-Л-К5 (Летнее)", "basis": "ст. Стенькино II", "transport": "rail"},
    "DSC5TLU005A": {"fuel": "ДТ-Л-К5 (Летнее)", "basis": "Тульская НБ", "transport": "auto"},
    "DSC5VON065J": {"fuel": "ДТ-Л-К5 (Летнее)", "basis": "ст. Войновка", "transport": "rail"},
    "DSC5VRZ005A": {"fuel": "ДТ-Л-К5 (Летнее)", "basis": "Воронежский цех", "transport": "auto"},
    "DSC5YAI065F": {"fuel": "ДТ-Л-К5 (Летнее)", "basis": "ст. Яничкино", "transport": "rail"},
    "DSC5ZEL065F": {"fuel": "ДТ-Л-К5 (Летнее)", "basis": "ст. Зелецино", "transport": "rail"},
    "DSC5ZEL065J": {"fuel": "ДТ-Л-К5 (Летнее)", "basis": "ст. Зелецино", "transport": "rail"},
    "DST5BYY001O": {"fuel": "ДТ-Л-К5 (Летнее)", "basis": "НП Брянск", "transport": "rail"},
    "DST5CHR001O": {"fuel": "ДТ-Л-К5 (Летнее)", "basis": "ЛПДС Черкассы", "transport": "rail"},
    "DST5NIK001O": {"fuel": "ДТ-Л-К5 (Летнее)", "basis": "ЛПДС Никольское-2", "transport": "rail"},
    "DST5NVL001O": {"fuel": "ДТ-Л-К5 (Летнее)", "basis": "ЛПДС Невская", "transport": "rail"},
    "DST5SLN001O": {"fuel": "ДТ-Л-К5 (Летнее)", "basis": "НС Солнечногорская", "transport": "rail"},
    "DST5VLD001O": {"fuel": "ДТ-Л-К5 (Летнее)", "basis": "ЛПДС Володарская", "transport": "rail"},
    "DST5VRN001O": {"fuel": "ДТ-Л-К5 (Летнее)", "basis": "ЛПДС Воронеж", "transport": "rail"},
    
    # Мазут топочный М100
    "M10ADZM065F": {"fuel": "Мазут топочный М100", "basis": "ст. Дземги", "transport": "rail"},
    "M12ZZAH060W": {"fuel": "Мазут топочный М100", "basis": "ст. Завережье-Экспорт", "transport": "rail"},
    "M16ANVY065F": {"fuel": "Мазут топочный М100", "basis": "ст. Новоярославская", "transport": "rail"},
    "M16ASTI065F": {"fuel": "Мазут топочный М100", "basis": "ст. Стенькино II", "transport": "rail"},
    "M30AANK065F": {"fuel": "Мазут топочный М100", "basis": "Ангарск-группа станций", "transport": "rail"},
    "M30ANOV065F": {"fuel": "Мазут топочный М100", "basis": "ст. Новая Еловка", "transport": "rail"},
    "M60AALL065J": {"fuel": "Мазут топочный М100", "basis": "ст. Аллагуват", "transport": "rail"},
    "M60ASSI065F": {"fuel": "Мазут топочный М100", "basis": "Саратов-группа станций", "transport": "rail"},
    "M60AYAI065F": {"fuel": "Мазут топочный М100", "basis": "ст. Яничкино", "transport": "rail"},
    "M70ASAU065F": {"fuel": "Мазут топочный М100", "basis": "Самара-группа станций", "transport": "rail"},
    "M70AUFM065F": {"fuel": "Мазут топочный М100", "basis": "Уфа-группа станций", "transport": "rail"},
    "MA11ZEL065J": {"fuel": "Мазут топочный М100", "basis": "ст. Зелецино", "transport": "rail"},
    
    # Топливо для реактивных двигателей ТС-1
    "JET-ANK065F": {"fuel": "Топливо для реактивных двигателей ТС-1", "basis": "Ангарск-группа станций", "transport": "rail"},
    "JET-KII065F": {"fuel": "Топливо для реактивных двигателей ТС-1", "basis": "ст. Кириши", "transport": "rail"},
    "JET-KII065S": {"fuel": "Топливо для реактивных двигателей ТС-1", "basis": "ст. Кириши", "transport": "rail"},
    "JET-KOB065F": {"fuel": "Топливо для реактивных двигателей ТС-1", "basis": "ст. Комбинатская", "transport": "rail"},
    "JET-NIH065F": {"fuel": "Топливо для реактивных двигателей ТС-1", "basis": "ст. Нижневартовск II", "transport": "rail"},
    "JET-NOV065F": {"fuel": "Топливо для реактивных двигателей ТС-1", "basis": "ст. Новая Еловка", "transport": "rail"},
    "JET-NVY065F": {"fuel": "Топливо для реактивных двигателей ТС-1", "basis": "ст. Новоярославская", "transport": "rail"},
    "JET-PDK065F": {"fuel": "Топливо для реактивных двигателей ТС-1", "basis": "Предкомбинатская-группа станций", "transport": "rail"},
    "JET-SUR060F": {"fuel": "Топливо для реактивных двигателей ТС-1", "basis": "ст. Сургут", "transport": "rail"},
    "JET1USI060F": {"fuel": "Топливо для реактивных двигателей ТС-1", "basis": "ст. Усинск", "transport": "rail"},
}